### ISSUE TITLE
release branch version still comes out as develop

### ISSUE THREAD

**Issue by rainbreak** [rainbreak/solidity-static#8]
```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.2-develop.2016.9.29+commit.af6afb04.Linux.g++
```

This is a problem when using a version pragma, as develop versions are considered strictly less than release.

**Comment by konradkonrad** [comment]
I believe you fixed this in fd46ecc7f97411ce91b2728df4be3bcf011113c2 :)
